source "http://gemcutter.org"
source "http://gems.github.com"

git "git://github.com/rails/rack.git"
git "git://github.com/rack/rack-contrib.git"

gem "jeweler"
gem "sinatra"
gem "thin"
gem "eventmachine"
gem "yajl-ruby", :require_as => "yajl/json_gem"
#gem "json"
gem "nokogiri"
gem "moneta"
gem "uuid"
gem "dm-core"
gem "dm-more", :require_as => nil
#gem "rack-tidy", :require_as "rack/tidy"
#gem "redis"
#gem "redis-namespace", :require_as => "redis/namespace"
#gem "gettext"